# Generated by Django 4.2.10 on 2024-03-04 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_data',
            fields=[
                ('cust_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('cust_name', models.CharField(default='none', max_length=200)),
                ('cust_age', models.IntegerField(default=20)),
                ('cust_problem', models.CharField(default=' ', max_length=255)),
                ('cust_dateofvisit', models.DateTimeField(default=' ')),
                ('cust_address', models.CharField(default=' ', max_length=255)),
                ('medicine_quant', models.CharField(default=' ', max_length=255)),
                ('cust_phn', models.IntegerField(default=9999999999)),
                ('cust_gender', models.CharField(default=None, max_length=255)),
                ('cust_dob', models.DateField(default=' ')),
                ('cust_email', models.EmailField(default=' ', max_length=254)),
            ],
            options={
                'db_table': 'Customer_data',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('med_price', models.IntegerField(default=100)),
                ('name', models.CharField(default='r', max_length=50)),
                ('batch_no', models.IntegerField(default=10)),
                ('expiry_date', models.DateField(default=' ')),
                ('manufac_date', models.DateField(default=' ')),
                ('shelf_number', models.CharField(default=2, max_length=255)),
                ('description', models.CharField(default='none', max_length=50)),
                ('in_stock_med', models.BooleanField(default=False)),
                ('Medicine_type', models.CharField(default='none', max_length=50)),
                ('Medicine_quantity', models.IntegerField(default=10)),
                ('medicine_location', models.CharField(default='hospital', max_length=255)),
                ('medicine_gst', models.FloatField(default=1.5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
