# Generated by Django 4.2.10 on 2024-03-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines_ap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_data',
            old_name='cust_id',
            new_name='id',
        ),
    ]
