# Generated by Django 5.0.3 on 2024-03-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicines_ap", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customer_data",
            table="customer_data_table",
        ),
    ]
