# Generated by Django 4.2.10 on 2024-03-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines_ap', '0002_rename_cust_id_customer_data_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_data',
            table='Customer_data_table',
        ),
    ]
